#![deny(warnings)]
#![warn(missing_docs)]
#![forbid(unsafe_code)]
// The README is the crate front page, and including it here doc-tests its
// code blocks so they can't drift from the API (same trick as `__skills`).
#![doc = include_str!("../README.md")]

// So that code generated by `misanthropic-derive` can name our own items by
// the absolute path `::misanthropic::…` even when expanded *inside* this crate
// (e.g. the `Notepad` tool). Same trick `serde` uses for `serde_derive`.
extern crate self as misanthropic;

pub mod key;
pub use key::Key;

pub mod client;
#[cfg(feature = "client")]
pub use client::Client;

#[cfg(feature = "dioxus")]
pub mod dioxus;

#[cfg(feature = "batch")]
pub mod batch;

pub mod model;
pub use model::{Id, Model, ModelInfo};

pub mod prompt;
pub use prompt::{CachedPrompt, Prompt};

/// Purely for doc testing the skill files
#[cfg(feature = "__skills")]
pub mod skills;

pub mod stream;
pub use stream::Stream;

pub mod tool;
pub use tool::Tool;

pub mod response;
pub use response::Response;

pub mod transport;
pub use transport::{Quirks, Transport};

#[cfg(feature = "markdown")]
/// Markdown utilities for parsing and rendering.
pub mod markdown;

#[cfg(feature = "html")]
/// Converts prompts and messages to HTML.
pub mod html;

#[cfg(feature = "cot")]
pub mod cot;

#[cfg(feature = "openai")]
#[allow(missing_docs)]
/// OpenAI-compatible types and conversions for use with Ollama and other
/// OpenAI-compatible endpoints.
pub mod openai;

#[cfg(not(feature = "langsan"))]
pub(crate) type CowStr = std::borrow::Cow<'static, str>;
#[cfg(feature = "langsan")]
pub(crate) type CowStr = langsan::CowStr<'static>;

/// Small utility functions and types.
pub(crate) mod utils;

/// Crate-internal, cross-cutting tests (the `wire_coverage` gate, …).
#[cfg(test)]
mod tests;

/// Re-exports of commonly used crates to avoid version conflicts and reduce
/// dependency bloat.
pub mod exports {
    pub use base64;
    pub use eventsource_stream;
    pub use futures;
    #[cfg(feature = "image")]
    pub use image;
    #[cfg(feature = "langsan")]
    pub use langsan;
    #[cfg(feature = "log")]
    pub use log;
    #[cfg(feature = "memsecurity")]
    pub use memsecurity;
    #[cfg(feature = "markdown")]
    pub use pulldown_cmark;
    #[cfg(feature = "markdown")]
    pub use pulldown_cmark_to_cmark;
    pub use reqwest;
    pub use serde;
    pub use serde_json;
}

/// Re-export of `serde_json::json!` for convenience because this is used
/// frequently.
pub use exports::serde_json::json;

/// Hidden re-exports for code generated by `misanthropic-derive`. Not a stable
/// API — generated code names these by path so downstream crates needn't add
/// `async_trait` to their own `Cargo.toml`.
#[cfg(feature = "derive")]
#[doc(hidden)]
#[allow(missing_docs)]
pub mod __derive {
    pub use async_trait;
    pub use serde_json;
}
