# Credit to GitHub Copilot for generating this file
name: Rust CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: llvm-tools-preview

      - name: Build
        run: cargo build --all-features --verbose

      - name: Check formatting
        run: cargo fmt --all -- --check

      - name: Clippy
        run: cargo clippy --all-features

      - name: Test
        run: cargo test --all-features --verbose

      # This should only happen on push to main. PRs should not upload coverage.
      - name: Install llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov
        if: matrix.os == 'ubuntu-latest' && github.event_name == 'push'

      - name: Install nextest
        uses: taiki-e/install-action@nextest
        if: matrix.os == 'ubuntu-latest' && github.event_name == 'push'

      - name: Write API key to api.key
        if: matrix.os == 'ubuntu-latest' && github.event_name == 'push'
        run: echo ${{ secrets.ANTHROPIC_API_KEY }} > api.key

      - name: Collect coverage data (including ignored tests)
        if: matrix.os == 'ubuntu-latest' && github.event_name == 'push'
        run: cargo llvm-cov nextest --all-features --run-ignored all --lcov --output-path lcov.info

      - name: Upload coverage to Codecov
        if: matrix.os == 'ubuntu-latest' && github.event_name == 'push'
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: lcov.info
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true
